---
- hosts: localhost
  gather_facts: yes
  connection: local
  vars:
    is_mac_os: "{{ ansible_os_family == 'Darwin' }}"
    is_debian_linux: "{{ ansible_os_family == 'Debian' }}"
    is_arch_linux: "{{ ansible_os_family == 'Archlinux' }}"
    is_windows: "{{ ansible_os_family == 'Windows' }}"
    homebrew_install_packages:
      - git
      - fzf
      - fd
      - nvim
      - most
      - htop
      - tmux
      - python3
      # - TODO exa replace with eza
      - micro
      # - TODO alacritty
      # - TODO https://www.nerdfonts.com/
      # - TODO chrome
      # - TODO firefox

  tasks:

    - name: Run if system is macOS
      include_tasks: tasks/macos.yml
      when: is_mac_os

    - name: Run if system is Debian Linux
      include_tasks: tasks/debian.yml
      when: is_debian_linux

    - name: Run if system is Arch Linux
      include_tasks: tasks/arch.yml
      when: is_arch_linux

    - name: Run if system is Windows
      include_tasks: tasks/windows.yml
      when: is_windows

    - name: Set up zshrc and oh-my-zsh
      include_tasks: tasks/zsh.yml

    - name: Set up config files
      include_tasks: tasks/config-files.yml
