---

- name: Check git is installed
  command: which git
  register: git_check
  failed_when:
    - git_check.rc != 0
  ignore_errors: false
  changed_when: false # Don't mark this as a change

- name: Clone oh-my-zsh
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "~/.oh-my-zsh"
    update: yes
  when: git_check.rc == 0

- name: Clone zsh-autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    update: yes
  when: git_check.rc == 0

- name: Clone zsh-syntax-highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    update: yes
  when: git_check.rc == 0

- name: Copy my oh-my-zsh theme to the custom themes directory
  copy:
    src: "files/config/zsh/addyi.zsh-theme"
    dest: "~/.oh-my-zsh/custom/themes/addyi.zsh-theme"
  when: git_check.rc == 0

- name: Copy my zshrc to the home directory
  copy:
    src: "files/config/zsh/zshrc"
    dest: "~/.zshrc"
    backup: true
  when: git_check.rc == 0
