# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

### THEME
ZSH_THEME="addyi" # custom theme

### UPDATE
zstyle ':omz:update' frequency 7 # Update frequency in days
zstyle ':omz:update' mode auto # update automatically without asking

### OMZ CONFIGURATION
# ENABLE_CORRECTION="true" # command auto-correction

### PLUGINS

# ssh-agend configuration
zstyle :omz:plugins:ssh-agent agent-forwarding yes
zstyle :omz:plugins:ssh-agent lazy yes

# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-prompt ssh-agent fzf fd gradle adb aliases archlinux zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

### USER CONFIGURATION
export EDITOR="nvim"

# source sdkman
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export ANDROID_HOME="$HOME/Library/Android/sdk"

### ALIASES
alias python="python3"
alias pip="pip3"
alias vim="nvim"

alias less="most"
alias more="most"

alias l="exa -la --git --header --group-directories-first"
alias ll="exa -la --git --header --group-directories-first"
alias tree="exa --tree --level=2 --git --header --group-directories-first"

alias cat="bat --paging=never"

alias gbv="git branch -vv"

alias zshconfig="vim ~/.zshrc"
alias vimconfig="vim ~/.config/nvim/init.vim"
alias omz="vim ~/.zshrc"

alias aliases="als" # aliases omz plugin
alias a="als" # aliases omz plugin
alias afind="alias | fzf"

alias yolo='git commit -m "$(curl -s https://whatthecommit.com/index.txt)"'

