---

- name: Check system is macOS
  fail:
    msg: "These tasks can only be run on macOS!"
  when: ansible_os_family != "Darwin"

- name: Install dependencies via Homebrew
  include_tasks: homebrew.yml
