# https://alacritty.org/config-alacritty.html

[font]
size = 16

# Colors (Ayu Light)
# https://github.com/alacritty/alacritty-theme/blob/master/themes/ayu_light.toml

# Change theme depending on system theme https://github.com/alacritty/alacritty/issues/5999#issuecomment-1100237805

[colors.primary]
background = '#FCFCFC'
foreground = '#5C6166'

[colors.normal]
black   = '#010101'
red     = '#e7666a'
green   = '#80ab24'
yellow  = '#eba54d'
blue    = '#4196df'
magenta = '#9870c3'
cyan    = '#51b891'
white   = '#c1c1c1'

[colors.bright]
black   = '#343434'
red     = '#ee9295'
green   = '#9fd32f'
yellow  = '#f0bc7b'
blue    = '#6daee6'
magenta = '#b294d2'
cyan    = '#75c7a8'
white   = '#dbdbdb'
