# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

### THEME
ZSH_THEME="addyi" # custom theme

### UPDATE
zstyle ':omz:update' frequency 7 # Update frequency in days
zstyle ':omz:update' mode auto # update automatically without asking

### OMZ CONFIGURATION
# ENABLE_CORRECTION="true" # command auto-correction

### PLUGINS

# ssh-agend configuration
zstyle :omz:plugins:ssh-agent agent-forwarding yes
zstyle :omz:plugins:ssh-agent lazy yes

# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-prompt ssh-agent fzf fd gradle adb aliases archlinux zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

### USER CONFIGURATION
export EDITOR="nvim"

### ALIASES
alias python="python3"
alias vim="nvim"

alias less="most"
alias more="most"

alias zshconfig="vim ~/.zshrc"
alias vimconfig="vim ~/.vimrc"
alias omz="vim ~/.zshrc"

alias aliases="acs" # aliases omz plugin
alias a="acs" # aliases omz plugin

alias yolo='git commit -m "$(curl -s https://whatthecommit.com/index.txt)"'
